package com.swisscom.treequest.domain;

public enum QuestTreeType {

  ROOT,
  ONLY_IN_INITIAL,
  IN_BOTH_TREES,
  ONLY_IN_NEW,
  CFS_TC_ACCOUNT_ROOT,
  CFS_TC_PRIVATE_IP_RANGE,
  CFS_CA_CERTIFICATE,
  CFS_TC_ACCOUNT,
  CFS_FOS,
  CFS_FOS_FW_RULES,
  CFS_VPN,
  CFS_INTEGRATION_VRF,
  CFS_LINK_TO_FIREWALL,
  CFS_LINK,
  CFS_SHARED_GROUP,
  CFS_DNS_SERVER,
  CFS_LE_GROUP,
  CFS_TC_SITE_ROOT,
  CFS_TC_ACCESS,
  CFS_TC_VLAN,
  CFS_LE_SITE_CONNECTION,
  CFS_LE_VLAN_DECL


}
