# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Build and unit test
          command: |
            mvn install
      - save_cache:
          paths:
            - ~/.m2
          key: hello-spring-mvn-V2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
  SCM:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
            fingerprints:
              - "f8:1f:5d:71:6b:ee:fa:e0:22:33:2f:3d:4d:31:59:1a"
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
            - hello-spring-mvn-V2
      - run:
          name: Create version and SCM Tags.
          command: |
             git config user.email ${GIT_EMAIL}
             git config user.name ${GIT_USER}
             ./mvnw -DskipTests=true -DscmCommentPrefix='[skip ci]' \
                -Dmaven.javadoc.failOnError=false \
                --batch-mode release:clean \
                release:prepare  -e

  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
     - checkout
     - restore_cache:
         keys:
           - hello-spring-mvn-V2-{{ checksum "pom.xml" }}
           - hello-spring-mvn-V2
     - run:
         name: build and push container
         command: |
           export PROJECT_VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout  | sed 's/-SNAPSHOT//')
           echo $PROJECT_VERSION
           cp .mvn/wrapper/settings.xml ~/.m2/settings.xml
           echo "<settingsSecurity><master>${maven_security_master}</master></settingsSecurity>" > ~/.m2/settings-security.xml
           ./mvnw compile jib:build -DskipTests=true \
              -Ddocker.tag=$PROJECT_VERSION \
              -Dbuild.num=$CIRCLE_BUILD_NUM
  deploy:
    docker:
      - image: google/cloud-sdk
    description: Deploy application to Google Kubernetes Engine
    working_directory: ~/repo
    steps:
      - checkout
      #Creating the Google cloud credentials JSON file.
      - run: echo ${GCLOUD_SERVICE_KEY} > key.json
      # Authentication in google cloud
      - run: gcloud auth activate-service-account --key-file key.json
      # setting the region used to deploy this image
      - run: gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      # Setting google clouse project to work.
      - run: gcloud config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: set the credentials to work with cluster
          command: |
            set +e
            gcloud container clusters get-credentials ${GOOGLE_CLUSTER_ID} --zone ${GOOGLE_COMPUTE_ZONE} --project ${GOOGLE_PROJECT_ID}

      # Generating the YAML file to deploy application. Get a template file(production-deployment.yaml.template.template) and setting the IMAGE_URL to be deployed.
      - run:
          name: generate deploy yaml file from the template file
          command: |
            cat "./k8s/production-deployment.yaml.template" | sed "s/{{imageURL}}/${PROJECT_IMAGE}$CIRCLE_PREVIOUS_BUILD_NUM/g" > ./k8s/production-deployment.yaml
          environment:
            PROJECT_IMAGE: registry.hub.docker.com\/victorsens\/tree-quest:circle_ci_build_
      - run: kubectl apply  -f ./k8s/
      - run: kubectl rollout status deployment/tree-quest-backend
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish-docker:
            context: GIT_CONFIGURATION
            requires:
              - build
      - deploy:
            context: GCP_CONFIGURATION
            requires:
              - publish-docker
      - SCM:
          context: GIT_CONFIGURATION
          requires:
            - publish-docker