
##################################################################################################
# Tree Guest services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: tree-guest
  labels:
    app: tree-guest
    service: tree-guest
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: tree-guest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tree-guest-service-account
  labels:
    account: tree-guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tree-guest-v1
  labels:
    app: tree-guest
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tree-guest
      version: v1
  template:
    metadata:
      labels:
        app: tree-guest
        version: v1
    spec:
      serviceAccountName: tree-guest-service-account
      containers:
      - name: tree-guest
        image: registry.hub.docker.com/victorsens/tree-quest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
