kind: Deployment
apiVersion: apps/v1
metadata:
  name: tree-guest-v1
  labels:
    app: tree-guest
    version: v1
spec:
  replicas: 1
  selector:
      matchLabels:
        app: tree-guest
        version: v1
  template:
    metadata:
      labels:
        app: tree-guest
        version: v1
    spec:
      serviceAccount: tree-guest-service-account
      containers:
      - name: tree-guest
        image: registry.hub.docker.com/victorsens/tree-quest
#        resources:
#          limits:
#            memory: "2048Mi"
#            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
#        readinessProbe:
#            httpGet:
#                path: /actuator/health
#                port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 5
