apiVersion: v1
kind: ServiceAccount
metadata:
  name: tree-guest-service-account
  labels:
    account: tree-guest
---
apiVersion: v1
kind: Service
metadata:
  name: tree-guest
  labels:
    app: tree-guest
    service: tree-guest
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: tree-guest