kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tree-quest-backend
spec:
  replicas: 1
  template:
    metadata:
      name: tree-quest-backend
      labels:
        app: tree-quest-backend
    spec:
      containers:
      - name: tree-quest
        image: victorsens/tree-quest:0.0.1-SNAPSHOT
        resources:
          limits:
            memory: "2048Mi"
            cpu: "100m"
        imagePullPolicy: Always

